# Индексация массива: доступ к отдельным элементам. 

In [1]:
import numpy as np
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

#print(x1)
#print(x2)
##print(x3)

Индексация как для стандартных списков Python

In [2]:
x1

array([0, 2, 6, 3, 1, 2])

In [3]:
x1[0]

0

In [4]:
x1[4]

1

In [5]:
x1[-1]

2

In [6]:
x1[-2]

1

In [7]:
x2

array([[6, 3, 5, 1],
       [0, 5, 5, 7],
       [9, 5, 5, 4]])

In [8]:
x2[1][3]

7

In [9]:
x2[2][-2]

5

In [10]:
x2[0][1] = 100

In [11]:
x2

array([[  6, 100,   5,   1],
       [  0,   5,   5,   7],
       [  9,   5,   5,   4]])

In [12]:
x2[0][1] = 101.5484

In [13]:
x2

array([[  6, 101,   5,   1],
       [  0,   5,   5,   7],
       [  9,   5,   5,   4]])

# Срезы массивов

Одномерные массивы

In [14]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x[:5] # первые пять элементов

array([0, 1, 2, 3, 4])

In [16]:
x[5:] # элементы после индекса = 5

array([5, 6, 7, 8, 9])

In [17]:
x[4:7] # подмассив из середины

array([4, 5, 6])

In [18]:
x[::2] # каждый второй элемент

array([0, 2, 4, 6, 8])

In [19]:
x[1::2] # каждый второй элемент, начиная с индекса 1

array([1, 3, 5, 7, 9])

In [20]:
x[::-1] # все элементы в обратном порядке

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
x[5::-2] # каждый второй элемент в обратном порядке, начиная с индекса 5

array([5, 3, 1])

Многомерные массивы

In [22]:
x2

array([[  6, 101,   5,   1],
       [  0,   5,   5,   7],
       [  9,   5,   5,   4]])

In [23]:
x2[:2, :3] # две строки и три столбца

array([[  6, 101,   5],
       [  0,   5,   5]])

In [24]:
x2[:3, ::2] # все строки, каждый второй столбец

array([[6, 5],
       [0, 5],
       [9, 5]])

Измерения массивов также можно переворачивать

In [25]:
x2[::-1, ::-1]

array([[  4,   5,   5,   9],
       [  7,   5,   5,   0],
       [  1,   5, 101,   6]])

Доступ к строкам и столбцам массива

In [26]:
print(x2[:, 0]) # первый столбец массива

[6 0 9]


In [27]:
print(x2[0, :]) # первая строка массива - эквивалентно x2[0]

[  6 101   5   1]


Подмассивы как предназначенные только для чтения представления

In [29]:
print(x2)

[[  6 101   5   1]
 [  0   5   5   7]
 [  9   5   5   4]]


In [32]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[  6 101]
 [  0   5]]


Если изменить подмассив исходный массив также изменится!

In [33]:
x2_sub[0, 1] = 8
print(x2_sub)

[[6 8]
 [0 5]]


In [34]:
print(x2)

[[6 8 5 1]
 [0 5 5 7]
 [9 5 5 4]]


Создание копий массивов

In [35]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[6 8]
 [0 5]]


In [36]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  8]
 [ 0  5]]


In [37]:
print(x2)

[[6 8 5 1]
 [0 5 5 7]
 [9 5 5 4]]


## Изменение формы массивов 

In [40]:
grid = np.arange(1, 10).reshape(3, 3) # поместить числа от 1 до 10 в таблицу 3х3
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

Преобразование в вектор-строку с помощью reshape

In [42]:
x.reshape((1, 3))

array([[1, 2, 3]])

Преобразование в вектор-строку посредством newaxis

In [44]:
x[np.newaxis, :]

array([[1, 2, 3]])

Преобразование в вектор столбец с помощью reshape

In [45]:
x.reshape(3, 1)

array([[1],
       [2],
       [3]])

Преобразование в вектор столбец с помощью newaxis

In [49]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Слияние и разбиение массивов

Метод np.concatenate принимает на входе кортеж или список массивов в качестве первого аргумента

In [51]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

Можно объединить более двух массивов одновременно

In [54]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))


[ 1  2  3  3  2  1 99 99 99]


Для объединения двух массивов можно также использовать np.concatenate:

In [56]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
print(grid)

[[1 2 3]
 [4 5 6]]


In [58]:
np.concatenate([grid, grid]) # слияние по первой оси координат

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [62]:
np.concatenate([grid, grid], axis=1) # слияние по второй оси координат(с индексом 0)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Для работы с массивами с различающимися измерениями удобнее и понятнее использовать функции np.vstack (вертикальное объединение) и np.hstack (горизонтальное объединение)

In [66]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
np.vstack([x, grid]) # объединяет массивы по вертикали

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [68]:
y = np.array([[99],
             [99]])
np.hstack([grid, y]) # объединяе массивы по горизонтали

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Функция np.dstack объединяе по третьей оси:

In [75]:
>>> a = np.array([[1],[2],[3]])
>>> b = np.array([[2],[3],[4]])
>>> np.dstack((a,b))

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])