# Основы NumPy

Импортируем NumPy

In [10]:
import numpy as np

Создание массива целых чисел:

In [18]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Массив размером 3x5 значений с плавающей точкой:

In [19]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Массив размером 3x5, заполненый значением 3.14:

In [21]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

Массив, заполненый линейной последовательностью, начинающейся с 0 и заканчивающейся 20, с шагом 2 (аналогично встроеной функции range()):

In [22]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Создаем массив из пяти значений, равномерно располагающихся между 0 и 1:

In [23]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Создаем массив размером 3х3, равномерно распределенных случайных значений от 0 до 1:

In [24]:
np.random.random((3, 3))

array([[0.17786785, 0.0586004 , 0.95536557],
       [0.49452095, 0.84839916, 0.91549007],
       [0.51770233, 0.77130455, 0.22645688]])

Создаем массив размером 3х3 нормально распределенных случайных значений с медианой 0 и стандартным отклонением 1:

In [27]:
np.random.normal(0, 1, (3, 3))

array([[-1.57005033,  1.16156253,  0.29646432],
       [-0.94564716, -1.61520925, -1.54261486],
       [ 0.75673362, -0.96721498, -1.04247997]])

Создаем массив размером 3х3 случайных целых чисел в промежутке (0, 10):

In [30]:
np.random.randint(0, 10, (3, 3))

array([[7, 5, 0],
       [0, 2, 3],
       [4, 4, 7]])

Создаем единичную матрицу размером 3х3:

In [34]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Создаем неиницилизированный массив из трех целочисленных значений. Значениями будут произвольные, случайно оказавшиеся в соответствующих ячейках памяти данные:

In [35]:
np.empty(3)

array([1., 1., 1.])