# Индексация массива: доступ к отдельным элементам. 

In [7]:
import numpy as np
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

#print(x1)
#print(x2)
##print(x3)

Индексация как для стандартных списков Python

In [8]:
x1

array([2, 0, 1, 1, 1, 3])

In [9]:
x1[0]

2

In [10]:
x1[4]

1

In [11]:
x1[-1]

3

In [12]:
x1[-2]

1

In [13]:
x2

array([[3, 8, 2, 8],
       [5, 7, 5, 8],
       [5, 9, 0, 0]])

In [14]:
x2[1][3]

8

In [15]:
x2[2][-2]

0

In [16]:
x2[0][1] = 100

In [17]:
x2

array([[  3, 100,   2,   8],
       [  5,   7,   5,   8],
       [  5,   9,   0,   0]])

In [18]:
x2[0][1] = 101.5484

In [19]:
x2

array([[  3, 101,   2,   8],
       [  5,   7,   5,   8],
       [  5,   9,   0,   0]])

# Срезы массивов

Одномерные массивы

In [21]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x[:5] # первые пять элементов

array([0, 1, 2, 3, 4])

In [25]:
x[5:] # элементы после индекса = 5

array([5, 6, 7, 8, 9])

In [26]:
x[4:7] # подмассив из середины

array([4, 5, 6])

In [27]:
x[::2] # каждый второй элемент

array([0, 2, 4, 6, 8])

In [28]:
x[1::2] # каждый второй элемент, начиная с индекса 1

array([1, 3, 5, 7, 9])

In [29]:
x[::-1] # все элементы в обратном порядке

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
x[5::-2] # каждый второй элемент в обратном порядке, начиная с индекса 5

array([5, 3, 1])

Многомерные массивы

In [31]:
x2

array([[  3, 101,   2,   8],
       [  5,   7,   5,   8],
       [  5,   9,   0,   0]])

In [32]:
x2[:2, :3] # две строки и три столбца

array([[  3, 101,   2],
       [  5,   7,   5]])

In [33]:
x2[:3, ::2] # все строки, каждый второй столбец

array([[3, 2],
       [5, 5],
       [5, 0]])

Измерения массивов также можно переворачивать

In [34]:
x2[::-1, ::-1]

array([[  0,   0,   9,   5],
       [  8,   5,   7,   5],
       [  8,   2, 101,   3]])

Доступ к строкам и столбцам массива

In [38]:
print(x2[:, 0]) # первый столбец массива

[3 5 5]


In [39]:
print(x2[0, :]) # первая строка массива - эквивалентно x2[0]

[  3 101   2   8]
